# Generated by Django 5.1.7 on 2025-03-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('file', models.FileField(upload_to='api/files/', verbose_name='Vídeo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Requisição',
                'ordering': ['prompt'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_response', models.TextField(verbose_name='Resposta do Gemini')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens Usados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.request', verbose_name='Prompt')),
            ],
            options={
                'verbose_name': 'Resposta',
                'ordering': ['ai_response', 'prompt'],
            },
        ),
    ]
